mindmap
software <br> development
 curiosity
  prevent burnout
  side projects
 coding
  strong types
  code reviews
 team
  learning
  bus factor
  oncall
  toil
 infrastructure
  migrations   
  failures
  zero downtime
  scaling
   sharding
 context
  feature set
  business context
  customers
   feedback
   real problems
  domain
   optimizatios
 failure modes
  data consistency
  poison pills
